FROM kimjbstar/node-nestjs
WORKDIR /usr/src/app
RUN mkdir /src
COPY src ./src 
COPY tests ./tests 
COPY cert ./cert 
COPY package.json package-lock.json tsconfig.json nodemon.json nodemon-debug.json tsconfig.build.json ormconfig.js ./ 
RUN npm install && npm run tsc
CMD ["npm", "run", "start"]
EXPOSE 3000 443