FROM node:10
WORKDIR /usr/src/app
RUN mkdir /src
COPY src ./src 
COPY package.json package-lock.json tsconfig.json nodemon.json tsconfig.build.json ./
RUN npm i -g @nestjs/cli
RUN npm install && npm run tsc
CMD ["npm", "run", "serve"]
EXPOSE 3000