FROM node:10
WORKDIR /usr/src/app
RUN mkdir /src
COPY migrations ./migrations
COPY src ./src 
COPY package.json package-lock.json tsconfig.json nodemon.json ./
RUN npm install && npm run tsc
CMD ["npm", "run", "serve"]
EXPOSE 3000