FROM kimjbstar/node-nestjs
WORKDIR /usr/src/app
RUN mkdir /src
COPY src ./src 
COPY tests ./tests 
COPY config ./config 
COPY package.json package-lock.json tsconfig.json nodemon.json tsconfig.build.json .sequelizerc ./
RUN npm install && npm run tsc
CMD ["npm", "run", "serve"]
EXPOSE 3000