service: just1s-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ap-northeast-1
  environment:
    DATABASE_HOST: ${self:custom.serviceDatabaseHost.${self:provider.stage}}
    DATABASE_USERNAME: ${self:custom.serviceDatabaseUsername.${self:provider.stage}}
    DATABASE_PASSWORD: ${self:custom.serviceDatabasePassword.${self:provider.stage}}
    DATABASE_DATABASE: ${self:custom.serviceDatabase.${self:provider.stage}}
    JWT_SECRET: ${self:custom.serviceJwtSecret.${self:provider.stage}}

custom:
  serviceDomain:
    development: dev-api.just1s.xyz
    production: api.just1s.xyz
  serviceDatabaseHost:
    development: ${ssm:/development/db/host}
    production: ${ssm:/production/db/host}
  serviceDatabase:
    development: ${ssm:/development/db/database}
    production: ${ssm:/production/db/database}
  serviceDatabaseUsername:
    development: ${ssm:/development/db/username}
    production: ${ssm:/production/db/username}
  serviceDatabasePassword:
    development: ${ssm:/development/db/password}
    production: ${ssm:/production/db/password}
  serviceJwtSecret:
    development: ${ssm:/jwt_secret}
    production: ${ssm:/jwt_secret}
  serverless-layers:
    functions:
      - main
    dependenciesPath: ./package.json
    layersDeploymentBucket: just1s-backend-node-module
  customDomain:
    domainName: ${self:custom.serviceDomain.${self:provider.stage}}
    stage: ${opt:stage, 'development'}
    certificateName: "*.just1s.xyz"
    endpointType: "regional"
    createRoute53Record: true
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false
    hostedZoneId: Z02288121UT1NKWXB7B5M

functions:
  main:
    handler: serverless.handler
    events:
      - http:
          cors: true
          path: "/"
          method: any
      - http:
          cors: true
          path: "{proxy+}"
          method: any

plugins:
  - serverless-layers
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
