service: just1s-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ap-northeast-1
  environment:
    TYPEORM_HOST: ${env:TYPEORM_HOST}
    TYPEORM_PORT: ${env:TYPEORM_PORT}
    TYPEORM_USERNAME: ${env:TYPEORM_USERNAME}
    TYPEORM_PASSWORD: ${env:TYPEORM_PASSWORD}
    TYPEORM_DATABASE: ${env:TYPEORM_DATABASE}
    EXPRESS_PORT: ${env:EXPRESS_PORT}
    JWT_SECRET: ${env:JWT_SECRET}
    JUST1S_PRIVATE_KEY: ${env:JUST1S_PRIVATE_KEY}
    JUST1S_CERT: ${env:JUST1S_CERT}

custom:
  serverless-layers:
    functions:
      - main
    dependenciesPath: ./package.json
    layersDeploymentBucket: just1s-backend-node-module
  customDomain:
    domainName: dev.just1s.xyz
    stage: development
    certificateName: "*.just1s.xyz"
    createRoute53Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false

functions:
  main:
    handler: serverless.handler
    events:
      - http:
          cors: true
          path: "/"
          method: any
      - http:
          cors: true
          path: "{proxy+}"
          method: any

plugins:
  - serverless-layers
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
