service: just1s-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  environment:
    TYPEORM_HOST: ${env:TYPEORM_HOST}
    TYPEORM_PORT: ${env:TYPEORM_PORT}
    TYPEORM_USERNAME: ${env:TYPEORM_USERNAME}
    TYPEORM_PASSWORD: ${env:TYPEORM_PASSWORD}
    TYPEORM_DATABASE: ${env:TYPEORM_DATABASE}
    EXPRESS_PORT: ${env:EXPRESS_PORT}
    JWT_SECRET: ${env:JWT_SECRET}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    JUST1S_PRIVATE_KEY: ${env:JUST1S_PRIVATE_KEY}
    JUST1S_CERT: ${env:JUST1S_CERT}

functions:
  main:
    handler: src/serverless.handler
    events:
      - http:
          method: any
          path: /{any+}
plugins:
  - serverless-webpack
  - serverless-offline
