'use strict';

var Sequelize = require('sequelize');

/**
 * Actions summary:
 *
 * createTable "ReviewCategories", deps: []
 * createTable "CarBrands", deps: []
 * createTable "StoreLikes", deps: []
 * createTable "StoreKeywords", deps: []
 * createTable "StoreImages", deps: []
 * createTable "Categories", deps: []
 * createTable "ReviewReplies", deps: []
 * createTable "ReviewLikes", deps: []
 * createTable "PostHits", deps: []
 * createTable "PostImages", deps: []
 * createTable "PostLikes", deps: []
 * createTable "PostReplies", deps: []
 * createTable "ReviewImages", deps: []
 * createTable "ReviewHits", deps: []
 * createTable "Users", deps: []
 * createTable "CarModelgroups", deps: [CarBrands]
 * createTable "Keywords", deps: [Categories]
 * createTable "Companies", deps: [Categories]
 * createTable "Stores", deps: [Users, Categories, Companies]
 * createTable "CarModels", deps: [CarBrands, CarModelgroups]
 * createTable "Posts", deps: [Users]
 * createTable "CarTrims", deps: [CarBrands, CarModelgroups, CarModels]
 * createTable "Reviews", deps: [CarModels, ReviewCategories, Users, Stores]
 * createTable "UserCars", deps: [Companies]
 * createTable "Cars", deps: [CarBrands, CarModelgroups, CarModels, CarTrims]
 * addIndex "likes-count-index" to table "Stores"
 *
 **/

var info = {
    "revision": 1,
    "name": "noname",
    "created": "2020-03-31T00:49:03.348Z",
    "comment": ""
};

var migrationCommands = [

    {
        fn: "createTable",
        params: [
            "ReviewCategories",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "name": {
                    "field": "name",
                    "_modelAttribute": true,
                    "fieldName": "name",
                    "type": STRING
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "parentId": {
                    "field": "parentId",
                    "_modelAttribute": true,
                    "fieldName": "parentId",
                    "allowNull": true,
                    "type": INTEGER,
                    "name": "parentId"
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "CarBrands",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "name": {
                    "field": "name",
                    "_modelAttribute": true,
                    "fieldName": "name",
                    "type": STRING
                },
                "isCertified": {
                    "field": "isCertified",
                    "_modelAttribute": true,
                    "fieldName": "isCertified",
                    "type": BOOLEAN
                },
                "imgUrl": {
                    "field": "imgUrl",
                    "_modelAttribute": true,
                    "fieldName": "imgUrl",
                    "type": STRING
                },
                "orderNo": {
                    "field": "orderNo",
                    "_modelAttribute": true,
                    "fieldName": "orderNo",
                    "type": INTEGER
                },
                "carsCount": {
                    "field": "carsCount",
                    "_modelAttribute": true,
                    "fieldName": "carsCount",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "StoreLikes",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "storeId": {
                    "field": "storeId",
                    "_modelAttribute": true,
                    "fieldName": "storeId",
                    "type": INTEGER
                },
                "userId": {
                    "field": "userId",
                    "_modelAttribute": true,
                    "fieldName": "userId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "StoreKeywords",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "storeId": {
                    "field": "storeId",
                    "_modelAttribute": true,
                    "fieldName": "storeId",
                    "type": INTEGER
                },
                "keywordId": {
                    "field": "keywordId",
                    "_modelAttribute": true,
                    "fieldName": "keywordId",
                    "type": INTEGER
                },
                "beginDate": {
                    "field": "beginDate",
                    "_modelAttribute": true,
                    "fieldName": "beginDate",
                    "type": DATEONLY
                },
                "endDate": {
                    "field": "endDate",
                    "_modelAttribute": true,
                    "fieldName": "endDate",
                    "type": DATEONLY
                },
                "status": {
                    "field": "status",
                    "_modelAttribute": true,
                    "fieldName": "status",
                    "values": ["NORMAL", "DELETED"],
                    "type": ENUM
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "StoreImages",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "storeId": {
                    "allowNull": true,
                    "name": "storeId",
                    "field": "storeId",
                    "_modelAttribute": true,
                    "fieldName": "storeId",
                    "type": INTEGER
                },
                "type": {
                    "field": "type",
                    "_modelAttribute": true,
                    "fieldName": "type",
                    "values": ["NORMAL", "CONTRACT", "PRICE"],
                    "type": ENUM
                },
                "url": {
                    "field": "url",
                    "_modelAttribute": true,
                    "fieldName": "url",
                    "type": STRING
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "Categories",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "type": {
                    "field": "type",
                    "_modelAttribute": true,
                    "fieldName": "type",
                    "values": ["STORE", "COMPANY", "STORE_COMPANY"],
                    "type": ENUM
                },
                "name": {
                    "field": "name",
                    "_modelAttribute": true,
                    "fieldName": "name",
                    "type": STRING
                },
                "orderNo": {
                    "field": "orderNo",
                    "_modelAttribute": true,
                    "fieldName": "orderNo",
                    "type": INTEGER
                },
                "status": {
                    "field": "status",
                    "_modelAttribute": true,
                    "fieldName": "status",
                    "values": ["ENABLED", "DISABLED"],
                    "type": ENUM
                },
                "storesCount": {
                    "field": "storesCount",
                    "_modelAttribute": true,
                    "fieldName": "storesCount",
                    "type": INTEGER
                },
                "companiesCount": {
                    "field": "companiesCount",
                    "_modelAttribute": true,
                    "fieldName": "companiesCount",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "ReviewReplies",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "reviewId": {
                    "field": "reviewId",
                    "_modelAttribute": true,
                    "fieldName": "reviewId",
                    "type": INTEGER
                },
                "userId": {
                    "field": "userId",
                    "_modelAttribute": true,
                    "fieldName": "userId",
                    "type": INTEGER
                },
                "content": {
                    "field": "content",
                    "_modelAttribute": true,
                    "fieldName": "content",
                    "type": STRING
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "parentId": {
                    "field": "parentId",
                    "_modelAttribute": true,
                    "fieldName": "parentId",
                    "allowNull": true,
                    "type": INTEGER,
                    "name": "parentId"
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "ReviewLikes",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "reviewId": {
                    "field": "reviewId",
                    "_modelAttribute": true,
                    "fieldName": "reviewId",
                    "type": INTEGER
                },
                "userId": {
                    "field": "userId",
                    "_modelAttribute": true,
                    "fieldName": "userId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "PostHits",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "postId": {
                    "field": "postId",
                    "_modelAttribute": true,
                    "fieldName": "postId",
                    "type": INTEGER
                },
                "userId": {
                    "field": "userId",
                    "_modelAttribute": true,
                    "fieldName": "userId",
                    "type": INTEGER
                },
                "ipAddress": {
                    "field": "ipAddress",
                    "_modelAttribute": true,
                    "fieldName": "ipAddress",
                    "type": STRING
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "PostImages",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "postId": {
                    "field": "postId",
                    "_modelAttribute": true,
                    "fieldName": "postId",
                    "type": INTEGER
                },
                "url": {
                    "field": "url",
                    "_modelAttribute": true,
                    "fieldName": "url",
                    "type": STRING
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "PostLikes",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "postId": {
                    "field": "postId",
                    "_modelAttribute": true,
                    "fieldName": "postId",
                    "type": INTEGER
                },
                "userId": {
                    "field": "userId",
                    "_modelAttribute": true,
                    "fieldName": "userId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "PostReplies",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "postId": {
                    "field": "postId",
                    "_modelAttribute": true,
                    "fieldName": "postId",
                    "type": INTEGER
                },
                "userId": {
                    "field": "userId",
                    "_modelAttribute": true,
                    "fieldName": "userId",
                    "type": INTEGER
                },
                "content": {
                    "field": "content",
                    "_modelAttribute": true,
                    "fieldName": "content",
                    "type": STRING
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "parentId": {
                    "field": "parentId",
                    "_modelAttribute": true,
                    "fieldName": "parentId",
                    "allowNull": true,
                    "type": INTEGER,
                    "name": "parentId"
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "ReviewImages",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "reviewId": {
                    "allowNull": true,
                    "name": "reviewId",
                    "field": "reviewId",
                    "_modelAttribute": true,
                    "fieldName": "reviewId",
                    "type": INTEGER
                },
                "url": {
                    "field": "url",
                    "_modelAttribute": true,
                    "fieldName": "url",
                    "type": STRING
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "ReviewHits",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "reviewId": {
                    "field": "reviewId",
                    "_modelAttribute": true,
                    "fieldName": "reviewId",
                    "type": INTEGER
                },
                "userId": {
                    "field": "userId",
                    "_modelAttribute": true,
                    "fieldName": "userId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "Users",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "role": {
                    "field": "role",
                    "_modelAttribute": true,
                    "fieldName": "role",
                    "values": ["NORMAL", "BUSINESS", "STAFF", "ADMIN"],
                    "type": ENUM
                },
                "email": {
                    "field": "email",
                    "_modelAttribute": true,
                    "fieldName": "email",
                    "type": STRING
                },
                "stringId": {
                    "field": "stringId",
                    "_modelAttribute": true,
                    "fieldName": "stringId",
                    "type": STRING
                },
                "pw": {
                    "field": "pw",
                    "_modelAttribute": true,
                    "fieldName": "pw",
                    "type": STRING
                },
                "imgUrl": {
                    "field": "imgUrl",
                    "_modelAttribute": true,
                    "fieldName": "imgUrl",
                    "type": STRING
                },
                "nickname": {
                    "field": "nickname",
                    "_modelAttribute": true,
                    "fieldName": "nickname",
                    "type": STRING
                },
                "name": {
                    "field": "name",
                    "_modelAttribute": true,
                    "fieldName": "name",
                    "type": STRING
                },
                "phoneNumber": {
                    "field": "phoneNumber",
                    "_modelAttribute": true,
                    "fieldName": "phoneNumber",
                    "type": STRING
                },
                "desc": {
                    "field": "desc",
                    "_modelAttribute": true,
                    "fieldName": "desc",
                    "type": STRING
                },
                "status": {
                    "field": "status",
                    "_modelAttribute": true,
                    "fieldName": "status",
                    "values": ["NORMAL", "WITHDRAWN"],
                    "type": ENUM
                },
                "blockedUntil": {
                    "field": "blockedUntil",
                    "_modelAttribute": true,
                    "fieldName": "blockedUntil",
                    "type": DATE
                },
                "toGetPushed": {
                    "field": "toGetPushed",
                    "_modelAttribute": true,
                    "fieldName": "toGetPushed",
                    "type": BOOLEAN
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "CarModelgroups",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "name": {
                    "field": "name",
                    "_modelAttribute": true,
                    "fieldName": "name",
                    "type": STRING
                },
                "isCertified": {
                    "field": "isCertified",
                    "_modelAttribute": true,
                    "fieldName": "isCertified",
                    "type": BOOLEAN
                },
                "carsCount": {
                    "field": "carsCount",
                    "_modelAttribute": true,
                    "fieldName": "carsCount",
                    "type": INTEGER
                },
                "encarCode": {
                    "field": "encarCode",
                    "_modelAttribute": true,
                    "fieldName": "encarCode",
                    "type": STRING
                },
                "orderNo": {
                    "field": "orderNo",
                    "_modelAttribute": true,
                    "fieldName": "orderNo",
                    "type": INTEGER
                },
                "carBrandId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "CarBrands",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "carBrandId",
                    "field": "carBrandId",
                    "_modelAttribute": true,
                    "fieldName": "carBrandId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "Keywords",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "name": {
                    "field": "name",
                    "_modelAttribute": true,
                    "fieldName": "name",
                    "type": STRING
                },
                "imgUrl": {
                    "field": "imgUrl",
                    "_modelAttribute": true,
                    "fieldName": "imgUrl",
                    "type": STRING
                },
                "status": {
                    "field": "status",
                    "_modelAttribute": true,
                    "fieldName": "status",
                    "values": ["ENABLED", "DISABLED"],
                    "type": ENUM
                },
                "orderNo": {
                    "field": "orderNo",
                    "_modelAttribute": true,
                    "fieldName": "orderNo",
                    "type": STRING
                },
                "storesCount": {
                    "field": "storesCount",
                    "_modelAttribute": true,
                    "fieldName": "storesCount",
                    "type": STRING
                },
                "categoryId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "Categories",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "categoryId",
                    "field": "categoryId",
                    "_modelAttribute": true,
                    "fieldName": "categoryId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "parentId": {
                    "field": "parentId",
                    "_modelAttribute": true,
                    "fieldName": "parentId",
                    "allowNull": true,
                    "type": INTEGER,
                    "name": "parentId"
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "Companies",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "name": {
                    "field": "name",
                    "_modelAttribute": true,
                    "fieldName": "name",
                    "type": STRING
                },
                "nationality": {
                    "field": "nationality",
                    "_modelAttribute": true,
                    "fieldName": "nationality",
                    "values": ["UNKNOWN", "DOMESTIC", "OVERSEAS"],
                    "type": ENUM
                },
                "repPhoneNumber": {
                    "field": "repPhoneNumber",
                    "_modelAttribute": true,
                    "fieldName": "repPhoneNumber",
                    "type": STRING
                },
                "imgUrl": {
                    "field": "imgUrl",
                    "_modelAttribute": true,
                    "fieldName": "imgUrl",
                    "type": STRING
                },
                "titleImgUrl": {
                    "field": "titleImgUrl",
                    "_modelAttribute": true,
                    "fieldName": "titleImgUrl",
                    "type": STRING
                },
                "sampleImgUrl": {
                    "field": "sampleImgUrl",
                    "_modelAttribute": true,
                    "fieldName": "sampleImgUrl",
                    "type": STRING
                },
                "linkUrl": {
                    "field": "linkUrl",
                    "_modelAttribute": true,
                    "fieldName": "linkUrl",
                    "type": STRING
                },
                "categoryId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "Categories",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "categoryId",
                    "field": "categoryId",
                    "_modelAttribute": true,
                    "fieldName": "categoryId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "Stores",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "level": {
                    "field": "level",
                    "_modelAttribute": true,
                    "fieldName": "level",
                    "values": ["NORMAL", "AFFILIATE", "EXCELLENT"],
                    "type": ENUM
                },
                "status": {
                    "field": "status",
                    "_modelAttribute": true,
                    "fieldName": "status",
                    "values": ["WATING", "HIDDEN", "NORMAL", "DELETED"],
                    "type": ENUM
                },
                "name": {
                    "field": "name",
                    "_modelAttribute": true,
                    "fieldName": "name",
                    "type": STRING
                },
                "stringId": {
                    "field": "stringId",
                    "_modelAttribute": true,
                    "fieldName": "stringId",
                    "type": STRING
                },
                "tel": {
                    "field": "tel",
                    "_modelAttribute": true,
                    "fieldName": "tel",
                    "type": STRING
                },
                "phoneNumber": {
                    "field": "phoneNumber",
                    "_modelAttribute": true,
                    "fieldName": "phoneNumber",
                    "type": STRING
                },
                "lat": {
                    "field": "lat",
                    "_modelAttribute": true,
                    "fieldName": "lat",
                    "type": DECIMAL
                },
                "lng": {
                    "field": "lng",
                    "_modelAttribute": true,
                    "fieldName": "lng",
                    "type": DECIMAL
                },
                "repImgUrl": {
                    "field": "repImgUrl",
                    "_modelAttribute": true,
                    "fieldName": "repImgUrl",
                    "type": STRING
                },
                "desc": {
                    "field": "desc",
                    "_modelAttribute": true,
                    "fieldName": "desc",
                    "type": STRING
                },
                "descImgUrl": {
                    "field": "descImgUrl",
                    "_modelAttribute": true,
                    "fieldName": "descImgUrl",
                    "type": STRING
                },
                "address1": {
                    "field": "address1",
                    "_modelAttribute": true,
                    "fieldName": "address1",
                    "type": STRING
                },
                "address2": {
                    "field": "address2",
                    "_modelAttribute": true,
                    "fieldName": "address2",
                    "type": STRING
                },
                "openingHours": {
                    "field": "openingHours",
                    "_modelAttribute": true,
                    "fieldName": "openingHours",
                    "type": STRING
                },
                "likesCount": {
                    "field": "likesCount",
                    "_modelAttribute": true,
                    "fieldName": "likesCount",
                    "type": INTEGER
                },
                "adminLikesCount": {
                    "field": "adminLikesCount",
                    "_modelAttribute": true,
                    "fieldName": "adminLikesCount",
                    "type": STRING
                },
                "reviewsCount": {
                    "field": "reviewsCount",
                    "_modelAttribute": true,
                    "fieldName": "reviewsCount",
                    "type": STRING
                },
                "ownerId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "Users",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "ownerId",
                    "field": "ownerId",
                    "_modelAttribute": true,
                    "fieldName": "ownerId",
                    "type": INTEGER
                },
                "categoryId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "Categories",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "categoryId",
                    "field": "categoryId",
                    "_modelAttribute": true,
                    "fieldName": "categoryId",
                    "type": INTEGER
                },
                "companyId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "Companies",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "companyId",
                    "field": "companyId",
                    "_modelAttribute": true,
                    "fieldName": "companyId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "CarModels",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "name": {
                    "field": "name",
                    "_modelAttribute": true,
                    "fieldName": "name",
                    "type": STRING
                },
                "isCertified": {
                    "field": "isCertified",
                    "_modelAttribute": true,
                    "fieldName": "isCertified",
                    "type": BOOLEAN
                },
                "yearBegin": {
                    "field": "yearBegin",
                    "_modelAttribute": true,
                    "fieldName": "yearBegin",
                    "type": STRING
                },
                "yearEnd": {
                    "field": "yearEnd",
                    "_modelAttribute": true,
                    "fieldName": "yearEnd",
                    "type": STRING
                },
                "carsCount": {
                    "field": "carsCount",
                    "_modelAttribute": true,
                    "fieldName": "carsCount",
                    "type": INTEGER
                },
                "sizeType": {
                    "field": "sizeType",
                    "_modelAttribute": true,
                    "fieldName": "sizeType",
                    "values": ["SMALL", "SEMI_MEDIUM", "MEDIUM", "SEMI_LARGE", "LARGE", "EXTRA_LARGE"],
                    "type": ENUM
                },
                "carBrandId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "CarBrands",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "carBrandId",
                    "field": "carBrandId",
                    "_modelAttribute": true,
                    "fieldName": "carBrandId",
                    "type": INTEGER
                },
                "carModelgroupId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "CarModelgroups",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "carModelgroupId",
                    "field": "carModelgroupId",
                    "_modelAttribute": true,
                    "fieldName": "carModelgroupId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "Posts",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "type": {
                    "field": "type",
                    "_modelAttribute": true,
                    "fieldName": "type",
                    "values": ["FREE", "NOTICE", "HELP", "FAQ", "TERM", "STORY"],
                    "type": ENUM
                },
                "subType": {
                    "field": "subType",
                    "_modelAttribute": true,
                    "fieldName": "subType",
                    "values": ["UNKNOWN", "NEWS", "LIFE", "CARRING_TV", "MOTOR_SPORTS"],
                    "type": ENUM
                },
                "status": {
                    "field": "status",
                    "_modelAttribute": true,
                    "fieldName": "status",
                    "values": ["NORMAL", "HIDDEN"],
                    "type": ENUM
                },
                "userId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "Users",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "userId",
                    "field": "userId",
                    "_modelAttribute": true,
                    "fieldName": "userId",
                    "type": INTEGER
                },
                "title": {
                    "field": "title",
                    "_modelAttribute": true,
                    "fieldName": "title",
                    "type": STRING
                },
                "content": {
                    "field": "content",
                    "_modelAttribute": true,
                    "fieldName": "content",
                    "type": STRING
                },
                "repImgUrl": {
                    "field": "repImgUrl",
                    "_modelAttribute": true,
                    "fieldName": "repImgUrl",
                    "type": STRING
                },
                "link": {
                    "field": "link",
                    "_modelAttribute": true,
                    "fieldName": "link",
                    "type": STRING
                },
                "repliesCount": {
                    "field": "repliesCount",
                    "_modelAttribute": true,
                    "fieldName": "repliesCount",
                    "type": INTEGER
                },
                "likesCount": {
                    "field": "likesCount",
                    "_modelAttribute": true,
                    "fieldName": "likesCount",
                    "type": INTEGER
                },
                "hitsCount": {
                    "field": "hitsCount",
                    "_modelAttribute": true,
                    "fieldName": "hitsCount",
                    "type": INTEGER
                },
                "adminHitsCount": {
                    "field": "adminHitsCount",
                    "_modelAttribute": true,
                    "fieldName": "adminHitsCount",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "CarTrims",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "name": {
                    "field": "name",
                    "_modelAttribute": true,
                    "fieldName": "name",
                    "type": STRING
                },
                "isCertified": {
                    "field": "isCertified",
                    "_modelAttribute": true,
                    "fieldName": "isCertified",
                    "type": BOOLEAN
                },
                "wd": {
                    "field": "wd",
                    "_modelAttribute": true,
                    "fieldName": "wd",
                    "values": ["UNKNOWN", "2WD", "4WD"],
                    "type": ENUM
                },
                "highestPrice": {
                    "field": "highestPrice",
                    "_modelAttribute": true,
                    "fieldName": "highestPrice",
                    "type": INTEGER
                },
                "carBrandId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "CarBrands",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "carBrandId",
                    "field": "carBrandId",
                    "_modelAttribute": true,
                    "fieldName": "carBrandId",
                    "type": INTEGER
                },
                "carModelgroupId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "CarModelgroups",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "carModelgroupId",
                    "field": "carModelgroupId",
                    "_modelAttribute": true,
                    "fieldName": "carModelgroupId",
                    "type": INTEGER
                },
                "carModelId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "CarModels",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "carModelId",
                    "field": "carModelId",
                    "_modelAttribute": true,
                    "fieldName": "carModelId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "Reviews",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "type": {
                    "field": "type",
                    "_modelAttribute": true,
                    "fieldName": "type",
                    "values": ["CUSTOMER", "STORE"],
                    "allowNull": false,
                    "type": ENUM
                },
                "title": {
                    "field": "title",
                    "_modelAttribute": true,
                    "fieldName": "title",
                    "validate": {
                        "notContains": {
                            "msg": "광고는 포함되선 안됩니다.",
                            "args": "광고"
                        },
                        "notEmpty": true
                    },
                    "allowNull": false,
                    "type": STRING
                },
                "content": {
                    "field": "content",
                    "_modelAttribute": true,
                    "fieldName": "content",
                    "allowNull": false,
                    "type": STRING
                },
                "workingHours": {
                    "field": "workingHours",
                    "_modelAttribute": true,
                    "fieldName": "workingHours",
                    "validate": {
                        "isNumeric": true
                    },
                    "allowNull": false,
                    "type": INTEGER
                },
                "price": {
                    "field": "price",
                    "_modelAttribute": true,
                    "fieldName": "price",
                    "validate": {
                        "isNumeric": true
                    },
                    "allowNull": false,
                    "type": INTEGER
                },
                "beforeImgUrl": {
                    "field": "beforeImgUrl",
                    "_modelAttribute": true,
                    "fieldName": "beforeImgUrl",
                    "allowNull": false,
                    "type": STRING
                },
                "repImgUrl": {
                    "field": "repImgUrl",
                    "_modelAttribute": true,
                    "fieldName": "repImgUrl",
                    "allowNull": false,
                    "type": STRING
                },
                "repliesCount": {
                    "field": "repliesCount",
                    "_modelAttribute": true,
                    "fieldName": "repliesCount",
                    "validate": {
                        "isNumeric": true
                    },
                    "allowNull": false,
                    "type": INTEGER
                },
                "likesCount": {
                    "field": "likesCount",
                    "_modelAttribute": true,
                    "fieldName": "likesCount",
                    "validate": {
                        "isNumeric": true
                    },
                    "allowNull": false,
                    "type": INTEGER
                },
                "hitsCount": {
                    "field": "hitsCount",
                    "_modelAttribute": true,
                    "fieldName": "hitsCount",
                    "validate": {
                        "isNumeric": true
                    },
                    "allowNull": false,
                    "type": INTEGER
                },
                "adminHitsCount": {
                    "field": "adminHitsCount",
                    "_modelAttribute": true,
                    "fieldName": "adminHitsCount",
                    "validate": {
                        "isNumeric": true
                    },
                    "allowNull": false,
                    "type": INTEGER
                },
                "status": {
                    "field": "status",
                    "_modelAttribute": true,
                    "fieldName": "status",
                    "values": ["HIDDEN", "NORMAL"],
                    "allowNull": false,
                    "type": ENUM
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "carModelId": {
                    "field": "carModelId",
                    "_modelAttribute": true,
                    "fieldName": "carModelId",
                    "onUpdate": "CASCADE",
                    "onDelete": "SET NULL",
                    "references": {
                        "model": "CarModels",
                        "key": "id"
                    },
                    "allowNull": true,
                    "type": INTEGER,
                    "name": "carModelId"
                },
                "reviewCategoryId": {
                    "field": "reviewCategoryId",
                    "_modelAttribute": true,
                    "fieldName": "reviewCategoryId",
                    "onUpdate": "CASCADE",
                    "onDelete": "SET NULL",
                    "references": {
                        "model": "ReviewCategories",
                        "key": "id"
                    },
                    "allowNull": true,
                    "type": INTEGER,
                    "name": "reviewCategoryId"
                },
                "userId": {
                    "field": "userId",
                    "_modelAttribute": true,
                    "fieldName": "userId",
                    "onUpdate": "CASCADE",
                    "onDelete": "SET NULL",
                    "references": {
                        "model": "Users",
                        "key": "id"
                    },
                    "allowNull": true,
                    "type": INTEGER,
                    "name": "userId"
                },
                "storeId": {
                    "field": "storeId",
                    "_modelAttribute": true,
                    "fieldName": "storeId",
                    "onUpdate": "CASCADE",
                    "onDelete": "SET NULL",
                    "references": {
                        "model": "Stores",
                        "key": "id"
                    },
                    "allowNull": true,
                    "type": INTEGER,
                    "name": "storeId"
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "UserCars",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "userId": {
                    "field": "userId",
                    "_modelAttribute": true,
                    "fieldName": "userId",
                    "type": INTEGER
                },
                "carModelId": {
                    "field": "carModelId",
                    "_modelAttribute": true,
                    "fieldName": "carModelId",
                    "type": INTEGER
                },
                "carNumber": {
                    "field": "carNumber",
                    "_modelAttribute": true,
                    "fieldName": "carNumber",
                    "type": STRING
                },
                "fuelType": {
                    "field": "fuelType",
                    "_modelAttribute": true,
                    "fieldName": "fuelType",
                    "values": ["UNKNOWN", "GOOD_GASOLINE", "GASOLINE", "DIESEL", "LPG", "HYBRID", "EV"],
                    "type": ENUM
                },
                "carYearMonth": {
                    "field": "carYearMonth",
                    "_modelAttribute": true,
                    "fieldName": "carYearMonth",
                    "type": STRING
                },
                "mileage": {
                    "field": "mileage",
                    "_modelAttribute": true,
                    "fieldName": "mileage",
                    "type": INTEGER
                },
                "insrExpiredDate": {
                    "field": "insrExpiredDate",
                    "_modelAttribute": true,
                    "fieldName": "insrExpiredDate",
                    "type": DATEONLY
                },
                "insrCompanyId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "Companies",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "insrCompanyId",
                    "field": "insrCompanyId",
                    "_modelAttribute": true,
                    "fieldName": "insrCompanyId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },

    {
        fn: "createTable",
        params: [
            "Cars",
            {
                "id": {
                    "field": "id",
                    "_modelAttribute": true,
                    "fieldName": "id",
                    "_autoGenerated": true,
                    "autoIncrement": true,
                    "primaryKey": true,
                    "allowNull": false,
                    "type": INTEGER
                },
                "fullName": {
                    "field": "fullName",
                    "_modelAttribute": true,
                    "fieldName": "fullName",
                    "type": STRING
                },
                "brandName": {
                    "field": "brandName",
                    "_modelAttribute": true,
                    "fieldName": "brandName",
                    "type": STRING
                },
                "modelgroupName": {
                    "field": "modelgroupName",
                    "_modelAttribute": true,
                    "fieldName": "modelgroupName",
                    "type": STRING
                },
                "modelName": {
                    "field": "modelName",
                    "_modelAttribute": true,
                    "fieldName": "modelName",
                    "type": STRING
                },
                "trimName": {
                    "field": "trimName",
                    "_modelAttribute": true,
                    "fieldName": "trimName",
                    "type": STRING
                },
                "isCertified": {
                    "field": "isCertified",
                    "_modelAttribute": true,
                    "fieldName": "isCertified",
                    "type": BOOLEAN
                },
                "carBrandId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "CarBrands",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "carBrandId",
                    "field": "carBrandId",
                    "_modelAttribute": true,
                    "fieldName": "carBrandId",
                    "type": INTEGER
                },
                "carModelgroupId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "CarModelgroups",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "carModelgroupId",
                    "field": "carModelgroupId",
                    "_modelAttribute": true,
                    "fieldName": "carModelgroupId",
                    "type": INTEGER
                },
                "carModelId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "CarModels",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "carModelId",
                    "field": "carModelId",
                    "_modelAttribute": true,
                    "fieldName": "carModelId",
                    "type": INTEGER
                },
                "carTrimId": {
                    "onUpdate": "CASCADE",
                    "onDelete": "NO ACTION",
                    "references": {
                        "model": "CarTrims",
                        "key": "id"
                    },
                    "allowNull": true,
                    "name": "carTrimId",
                    "field": "carTrimId",
                    "_modelAttribute": true,
                    "fieldName": "carTrimId",
                    "type": INTEGER
                },
                "createdAt": {
                    "field": "createdAt",
                    "_modelAttribute": true,
                    "fieldName": "createdAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                },
                "updatedAt": {
                    "field": "updatedAt",
                    "_modelAttribute": true,
                    "fieldName": "updatedAt",
                    "_autoGenerated": true,
                    "allowNull": false,
                    "type": DATE
                }
            },
            {}
        ]
    },
    {
        fn: "addIndex",
        params: [
            "Stores",
            [{
                "name": "likesCount"
            }],
            {
                "indexName": "likes-count-index"
            }
        ]
    }
];

var rollbackCommands = [{
        fn: "dropTable",
        params: ["Posts"]
    },
    {
        fn: "dropTable",
        params: ["CarBrands"]
    },
    {
        fn: "dropTable",
        params: ["CarModelgroups"]
    },
    {
        fn: "dropTable",
        params: ["CarTrims"]
    },
    {
        fn: "dropTable",
        params: ["Cars"]
    },
    {
        fn: "dropTable",
        params: ["Categories"]
    },
    {
        fn: "dropTable",
        params: ["Companies"]
    },
    {
        fn: "dropTable",
        params: ["Keywords"]
    },
    {
        fn: "dropTable",
        params: ["PostHits"]
    },
    {
        fn: "dropTable",
        params: ["PostImages"]
    },
    {
        fn: "dropTable",
        params: ["PostLikes"]
    },
    {
        fn: "dropTable",
        params: ["PostReplies"]
    },
    {
        fn: "dropTable",
        params: ["CarModels"]
    },
    {
        fn: "dropTable",
        params: ["ReviewCategories"]
    },
    {
        fn: "dropTable",
        params: ["ReviewHits"]
    },
    {
        fn: "dropTable",
        params: ["ReviewImages"]
    },
    {
        fn: "dropTable",
        params: ["ReviewLikes"]
    },
    {
        fn: "dropTable",
        params: ["ReviewReplies"]
    },
    {
        fn: "dropTable",
        params: ["Reviews"]
    },
    {
        fn: "dropTable",
        params: ["StoreImages"]
    },
    {
        fn: "dropTable",
        params: ["StoreKeywords"]
    },
    {
        fn: "dropTable",
        params: ["StoreLikes"]
    },
    {
        fn: "dropTable",
        params: ["Stores"]
    },
    {
        fn: "dropTable",
        params: ["UserCars"]
    },
    {
        fn: "dropTable",
        params: ["Users"]
    }
];

module.exports = {
    pos: 0,
    up: function(queryInterface, Sequelize)
    {
        var index = this.pos;
        return new Promise(function(resolve, reject) {
            function next() {
                if (index < migrationCommands.length)
                {
                    let command = migrationCommands[index];
                    console.log("[#"+index+"] execute: " + command.fn);
                    index++;
                    queryInterface[command.fn].apply(queryInterface, command.params).then(next, reject);
                }
                else
                    resolve();
            }
            next();
        });
    },
    down: function(queryInterface, Sequelize)
    {
        var index = this.pos;
        return new Promise(function(resolve, reject) {
            function next() {
                if (index < rollbackCommands.length)
                {
                    let command = rollbackCommands[index];
                    console.log("[#"+index+"] execute: " + command.fn);
                    index++;
                    queryInterface[command.fn].apply(queryInterface, command.params).then(next, reject);
                }
                else
                    resolve();
            }
            next();
        });
    },
    info: info
};
