name: Deploy
on:
  push:
    branches:
      - development
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          stage: development
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TYPEORM_HOST: ${secrets:TYPEORM_HOST}
          TYPEORM_PORT: ${secrets:TYPEORM_PORT}
          TYPEORM_USERNAME: ${secrets:TYPEORM_USERNAME}
          TYPEORM_PASSWORD: ${secrets:TYPEORM_PASSWORD}
          TYPEORM_DATABASE: ${secrets:TYPEORM_DATABASE}
          EXPRESS_PORT: ${secrets:EXPRESS_PORT}
          JWT_SECRET: ${secrets:JWT_SECRET}
          JUST1S_PRIVATE_KEY: ${secrets:JUST1S_PRIVATE_KEY}
          JUST1S_CERT: ${secrets:JUST1S_CERT}
